version: "3.8"

services:
  nest:
    build: .
    image: zy/dm-nest:0.0.4
    ports:
      - "3001:3000"
    depends_on:
      - mysql
    env_file:
      - .env.production
    restart: "always"

  mysql:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    env_file:
      - .env.production

volumes:
  mysql_data:
