version: "3.8"

services:
  nest:
    build: .
    image: zy/nest-blog:0.0.4
    container_name: nest
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: mysql://root:pswd@mysql:3306/nest_blog_prod
    restart: "always"

networks:
 default:
   external: true
   name: basic_default
