version: "3.8"

services:
  nest:
    build: .
    image: zy/nest-blog:0.0.1
    container_name: nest
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://root:pswd@mysql:3306/nest_blog_prod
    restart: "always"

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3307:3306"
    volumes:
      - nest-blog/conf:/etc/mysql/my.cnf
      - nest-blog/data:/var/lib/mysql

# networks:
#   default:
#     external: true
#     name: basic_default

volumes:
  mysql:
    name: nest-blog
