version: '3.8'

services:
  nest:
    image: varzy/dm-nest:latest
    ports:
      - '3001:3000'
    depends_on:
      - mysql
    env_file:
      - .env.production
    restart: 'always'

  mysql:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - '3307:3306'
    env_file:
      - .env.production

volumes:
  mysql_data:
    name: dm_blog_mysql_data
